"use client";

import { BrandStrategy } from "@/lib/types";
import { Users, Target, MessageSquare, Lightbulb, Award, TrendingUp, Download } from "lucide-react";
import { jsPDF } from "jspdf";

interface BrandAnalyzerProps {
  strategy: BrandStrategy | null;
  isAnalyzing: boolean;
  onAnalyze: () => void;
  hasImage: boolean;
  imagePreview?: string;
}

export function BrandAnalyzer({
  strategy,
  isAnalyzing,
  onAnalyze,
  hasImage,
  imagePreview,
}: BrandAnalyzerProps) {
  const exportToPDF = () => {
    if (!strategy) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    // Helper function to add text with word wrap
    const addText = (text: string, fontSize: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
      doc.setFontSize(fontSize);
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      doc.setTextColor(color[0], color[1], color[2]);
      const lines = doc.splitTextToSize(text, maxWidth);
      
      // Check if we need a new page
      if (yPosition + lines.length * fontSize * 0.5 > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      
      doc.text(lines, margin, yPosition);
      yPosition += lines.length * fontSize * 0.5 + 5;
    };

    const addSection = (title: string) => {
      yPosition += 5;
      addText(title, 14, true, [139, 92, 246]); // Purple color
      yPosition += 3;
    };

    // Title
    doc.setFillColor(139, 92, 246);
    doc.rect(0, 0, pageWidth, 30, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Brand Strategy Report", margin, 20);
    
    yPosition = 45;
    doc.setTextColor(0, 0, 0);

    // Brand Archetype
    addSection("BRAND ARCHETYPE");
    addText(strategy.brandArchetype, 16, true, [139, 92, 246]);
    addText(strategy.archetypeDescription, 11);

    // Positioning Statement
    addSection("POSITIONING STATEMENT");
    addText(`"${strategy.positioningStatement}"`, 11, false, [80, 80, 80]);

    // Target Audience
    addSection("TARGET AUDIENCE");
    addText("Demographics:", 11, true);
    addText(strategy.targetAudience.demographics, 10);
    addText("Psychographics:", 11, true);
    addText(strategy.targetAudience.psychographics, 10);
    addText("Interests:", 11, true);
    addText(strategy.targetAudience.interests.join(", "), 10);
    addText("Pain Points:", 11, true);
    strategy.targetAudience.painPoints.forEach((point) => {
      addText(`• ${point}`, 10);
    });
    addText("Aspirations:", 11, true);
    strategy.targetAudience.aspirations.forEach((aspiration) => {
      addText(`★ ${aspiration}`, 10);
    });

    // Messaging Pillars
    addSection("MESSAGING PILLARS");
    strategy.messagingPillars.forEach((pillar, idx) => {
      addText(`${idx + 1}. ${pillar}`, 11, true);
    });

    // Content Themes
    addSection("CONTENT THEMES");
    addText(strategy.contentThemes.join(" • "), 10);

    // Sample Posts
    addSection("SAMPLE POSTS");
    strategy.samplePosts.forEach((post) => {
      addText(`${post.platform} (${post.bestTime})`, 12, true);
      addText("Caption:", 10, true);
      addText(post.caption, 10);
      addText("Hooks:", 10, true);
      post.hooks.forEach((hook, idx) => {
        addText(`${idx + 1}. ${hook}`, 9);
      });
      addText("Hashtags:", 10, true);
      addText(post.hashtags.map(tag => `#${tag}`).join(" "), 9, false, [59, 130, 246]);
      yPosition += 5;
    });

    // Competitive Advantage
    addSection("COMPETITIVE ADVANTAGE");
    addText(strategy.competitiveAdvantage, 11);

    // Footer
    const timestamp = new Date().toLocaleString();
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(`Generated by BrandFactory on ${timestamp}`, margin, pageHeight - 10);

    // Save PDF
    doc.save(`brand-strategy-${Date.now()}.pdf`);
  };

  return (
    <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <Target className="h-5 w-5 text-purple-400" />
            Brand Strategy
          </h3>
          <p className="text-sm text-zinc-500 mt-1">
            AI-powered audience & messaging analysis
          </p>
        </div>
        <div className="flex items-center gap-2">
          {strategy && !isAnalyzing && (
            <button
              onClick={exportToPDF}
              className="rounded-lg px-4 py-2 text-sm font-medium transition-all bg-purple-500/10 text-purple-400 hover:bg-purple-500/20 border border-purple-500/20 flex items-center gap-2"
            >
              <Download className="h-4 w-4" />
              Export PDF
            </button>
          )}
          <button
            onClick={onAnalyze}
            disabled={!hasImage || isAnalyzing}
            className={`rounded-lg px-4 py-2 text-sm font-medium transition-all ${
              !hasImage || isAnalyzing
                ? "bg-zinc-800 text-zinc-600 cursor-not-allowed"
                : "bg-purple-500/10 text-purple-400 hover:bg-purple-500/20 border border-purple-500/20"
            }`}
          >
            {isAnalyzing ? (
              <span className="flex items-center gap-2">
                <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Analyzing...
              </span>
            ) : (
              "Analyze"
            )}
          </button>
        </div>
      </div>

      {/* Image preview with scanning effect */}
      {imagePreview && (
        <div className="mb-6">
          <div className="relative rounded-xl overflow-hidden bg-zinc-900 border border-zinc-800">
            <img 
              src={imagePreview} 
              alt="Preview" 
              className="w-full h-48 object-cover"
            />
            
            {/* Scanning overlay when analyzing */}
            {isAnalyzing && (
              <div className="absolute inset-0">
                {/* Dark overlay */}
                <div className="absolute inset-0 bg-black/40" />
                
                {/* Scanning line */}
                <div className="absolute inset-0 overflow-hidden">
                  <div className="absolute w-full h-1 bg-gradient-to-r from-transparent via-purple-400 to-transparent animate-scan shadow-[0_0_20px_rgba(168,85,247,0.8)]" />
                </div>
                
                {/* Grid overlay */}
                <div className="absolute inset-0 opacity-30" style={{
                  backgroundImage: `
                    linear-gradient(rgba(168, 85, 247, 0.3) 1px, transparent 1px),
                    linear-gradient(90deg, rgba(168, 85, 247, 0.3) 1px, transparent 1px)
                  `,
                  backgroundSize: '20px 20px'
                }} />
                
                {/* Corner markers */}
                <div className="absolute top-2 left-2 w-4 h-4 border-t-2 border-l-2 border-purple-400" />
                <div className="absolute top-2 right-2 w-4 h-4 border-t-2 border-r-2 border-purple-400" />
                <div className="absolute bottom-2 left-2 w-4 h-4 border-b-2 border-l-2 border-purple-400" />
                <div className="absolute bottom-2 right-2 w-4 h-4 border-b-2 border-r-2 border-purple-400" />
                
                {/* Center text */}
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="text-purple-400 text-sm font-bold tracking-wider animate-pulse">
                    ANALYZING BRAND
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {!strategy && !isAnalyzing && !imagePreview && (
        <div className="text-center py-12 text-zinc-600">
          <Users className="h-12 w-12 mx-auto mb-3 opacity-50" />
          <p className="text-sm">Upload a brand image and click Analyze for strategic insights</p>
        </div>
      )}

      {isAnalyzing && !imagePreview && (
        <div className="text-center py-12">
          <div className="inline-flex items-center gap-3 text-purple-400">
            <svg className="h-6 w-6 animate-spin" viewBox="0 0 24 24" fill="none">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
            <span className="text-sm font-medium">Building brand strategy...</span>
          </div>
        </div>
      )}

      {strategy && !isAnalyzing && (
        <div className="space-y-6">
          {/* Brand Archetype */}
          <div className="rounded-xl border border-purple-500/30 bg-purple-500/5 p-4">
            <div className="flex items-center gap-2 mb-2">
              <Award className="h-5 w-5 text-purple-400" />
              <h4 className="text-base font-bold text-white">Brand Archetype</h4>
            </div>
            <div className="text-2xl font-bold text-purple-400 mb-2">
              {strategy.brandArchetype}
            </div>
            <p className="text-sm text-zinc-300">{strategy.archetypeDescription}</p>
          </div>

          {/* Positioning Statement */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Target className="h-4 w-4 text-purple-400" />
              <h4 className="text-sm font-bold text-white uppercase tracking-wider">
                Positioning Statement
              </h4>
            </div>
            <p className="text-base text-zinc-100 italic leading-relaxed border-l-4 border-purple-500 pl-4 py-2 bg-zinc-800/30">
              "{strategy.positioningStatement}"
            </p>
          </div>

          {/* Target Audience */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Users className="h-4 w-4 text-purple-400" />
              <h4 className="text-sm font-bold text-white uppercase tracking-wider">
                Target Audience
              </h4>
            </div>
            <div className="space-y-3 rounded-lg border border-zinc-800 bg-zinc-900/30 p-4">
              <div>
                <div className="text-xs font-bold text-zinc-500 uppercase mb-1">Demographics</div>
                <p className="text-sm text-zinc-300">{strategy.targetAudience.demographics}</p>
              </div>
              <div>
                <div className="text-xs font-bold text-zinc-500 uppercase mb-1">Psychographics</div>
                <p className="text-sm text-zinc-300">{strategy.targetAudience.psychographics}</p>
              </div>
              <div>
                <div className="text-xs font-bold text-zinc-500 uppercase mb-1">Interests</div>
                <div className="flex flex-wrap gap-1.5">
                  {strategy.targetAudience.interests.map((interest, idx) => (
                    <span
                      key={idx}
                      className="rounded-full bg-purple-500/20 px-3 py-1 text-xs text-purple-300"
                    >
                      {interest}
                    </span>
                  ))}
                </div>
              </div>
              <div>
                <div className="text-xs font-bold text-zinc-500 uppercase mb-1">Pain Points</div>
                <ul className="space-y-1">
                  {strategy.targetAudience.painPoints.map((point, idx) => (
                    <li key={idx} className="flex items-start gap-2 text-sm text-zinc-400">
                      <span className="text-red-400 mt-0.5">•</span>
                      {point}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <div className="text-xs font-bold text-zinc-500 uppercase mb-1">Aspirations</div>
                <ul className="space-y-1">
                  {strategy.targetAudience.aspirations.map((aspiration, idx) => (
                    <li key={idx} className="flex items-start gap-2 text-sm text-zinc-400">
                      <span className="text-green-400 mt-0.5">★</span>
                      {aspiration}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Messaging Pillars */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <MessageSquare className="h-4 w-4 text-purple-400" />
              <h4 className="text-sm font-bold text-white uppercase tracking-wider">
                Messaging Pillars
              </h4>
            </div>
            <div className="grid grid-cols-2 gap-2">
              {strategy.messagingPillars.map((pillar, idx) => (
                <div
                  key={idx}
                  className="rounded-lg border border-zinc-800 bg-zinc-900/30 p-3 text-center"
                >
                  <span className="text-sm font-medium text-white">{pillar}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Content Themes */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Lightbulb className="h-4 w-4 text-purple-400" />
              <h4 className="text-sm font-bold text-white uppercase tracking-wider">
                Content Themes
              </h4>
            </div>
            <div className="flex flex-wrap gap-2">
              {strategy.contentThemes.map((theme, idx) => (
                <span
                  key={idx}
                  className="rounded-lg border border-zinc-700 bg-zinc-800/50 px-3 py-1.5 text-xs text-zinc-300"
                >
                  {theme}
                </span>
              ))}
            </div>
          </div>

          {/* Sample Posts */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <TrendingUp className="h-4 w-4 text-purple-400" />
              <h4 className="text-sm font-bold text-white uppercase tracking-wider">
                Sample Posts
              </h4>
            </div>
            <div className="space-y-4">
              {strategy.samplePosts.map((post, idx) => (
                <div
                  key={idx}
                  className="rounded-lg border border-zinc-800 bg-zinc-900/30 p-4"
                >
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-sm font-bold text-white">{post.platform}</span>
                    <span className="rounded-full bg-zinc-800 px-2 py-1 text-[10px] text-zinc-500">
                      {post.bestTime}
                    </span>
                  </div>

                  <div className="mb-3">
                    <div className="text-xs font-bold text-zinc-500 uppercase mb-2">Caption</div>
                    <p className="text-sm text-zinc-300 leading-relaxed">{post.caption}</p>
                  </div>

                  <div className="mb-3">
                    <div className="text-xs font-bold text-zinc-500 uppercase mb-2">Hook Options</div>
                    <div className="space-y-1.5">
                      {post.hooks.map((hook, hookIdx) => (
                        <div
                          key={hookIdx}
                          className="rounded bg-zinc-800/50 px-3 py-2 text-xs text-zinc-400"
                        >
                          {hookIdx + 1}. {hook}
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <div className="text-xs font-bold text-zinc-500 uppercase mb-2">Hashtags</div>
                    <div className="flex flex-wrap gap-1.5">
                      {post.hashtags.map((tag, tagIdx) => (
                        <span
                          key={tagIdx}
                          className="rounded bg-blue-500/10 px-2 py-1 text-[10px] text-blue-400"
                        >
                          #{tag}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Competitive Advantage */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Award className="h-4 w-4 text-purple-400" />
              <h4 className="text-sm font-bold text-white uppercase tracking-wider">
                Competitive Advantage
              </h4>
            </div>
            <p className="text-sm text-zinc-300 leading-relaxed rounded-lg border border-zinc-800 bg-zinc-900/30 p-4">
              {strategy.competitiveAdvantage}
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
